import js from '@eslint/js';
import globals from 'globals';

export default [
  {
    ignores: [
      '**/node_modules/**',
      'backend/data/**',
      // Generated by scripts/sync-card-art.js — large static card lists.
      'frontend/js/cards.js',
      'frontend/js/falling-cards.js',
    ],
  },

  // Backend: CommonJS on Node.
  {
    files: ['backend/**/*.js'],
    ...js.configs.recommended,
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'commonjs',
      globals: globals.node,
    },
    rules: {
      ...js.configs.recommended.rules,
      // Unused function args are common in express handlers (`next` on the
      // error middleware) and reporting them finds no bugs.
      'no-unused-vars': ['error', { args: 'none', caughtErrors: 'none' }],
      // `try { ... } catch {}` is used deliberately for best-effort work that
      // must never fail a request (SSE writes, push sends).
      'no-empty': ['error', { allowEmptyCatch: true }],
    },
  },

  // Frontend: classic <script> files sharing one global scope.
  {
    files: ['frontend/js/**/*.js', 'frontend/sw.js'],
    ...js.configs.recommended,
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'script',
      globals: { ...globals.browser, ...globals.serviceworker },
    },
    rules: {
      ...js.configs.recommended.rules,
      // Every frontend file is loaded as a plain script into one shared global
      // scope, so functions defined in api.js are undeclared as far as
      // leaderboard.js is concerned. ESLint scopes per file and cannot see
      // that, so no-undef would report ~350 false positives and bury the rules
      // that do find real bugs. Left off deliberately.
      'no-undef': 'off',
      // Same reason: a top-level function here is the file's public surface,
      // called from another script or an inline onclick — not dead code.
      'no-unused-vars': ['error', { args: 'none', caughtErrors: 'none', vars: 'local' }],
      'no-empty': ['error', { allowEmptyCatch: true }],
    },
  },
];
