const express = require('express');
const router = express.Router();
const fs = require('fs');
const path = require('path');

const CARDS_DIR = path.join(__dirname, '..', '..', 'frontend', 'dominion-cards-used-small');

// Turn a raw filename into a readable card name:
//   300px-Gold_Mine-100x160.jpg -> "Gold Mine"
//   anvil-100x160.jpg           -> "Anvil"
function labelFor(filename) {
  return filename
    .replace(/\.(png|jpg|webp)$/i, '')
    .replace(/^300px-/, '')
    .replace(/-\d+x\d+$/, '')
    .replace(/[_-]+/g, ' ')
    .trim()
    .replace(/\b\w/g, c => c.toUpperCase());
}

// Hardcoded fallback — used when the frontend assets directory isn't accessible
// (e.g. backend-only Docker container). Keep sorted by label.
const CARDS_FALLBACK = [
  { filename: "abandoned-mine-100x159.jpg"                    , label: "Abandoned Mine" },
  { filename: "Abundance-100x160.jpg"                         , label: "Abundance" },
  { filename: "300px-Alley-100x160.jpg"                       , label: "Alley" },
  { filename: "altar-100x159.jpg"                             , label: "Altar" },
  { filename: "anvil-100x160.jpg"                             , label: "Anvil" },
  { filename: "archive-100x160.jpg"                           , label: "Archive" },
  { filename: "300px-Aristocrat-100x160.jpg"                  , label: "Aristocrat" },
  { filename: "armory-100x159.jpg"                            , label: "Armory" },
  { filename: "artisan-100x159.jpg"                           , label: "Artisan" },
  { filename: "300px-Artist-100x160.jpg"                      , label: "Artist" },
  { filename: "astrolabe-100x160.jpg"                         , label: "Astrolabe" },
  { filename: "band-of-misfits-100x159.jpg"                   , label: "Band Of Misfits" },
  { filename: "bandit-100x160.jpg"                            , label: "Bandit" },
  { filename: "bandit-camp-100x159.jpg"                       , label: "Bandit Camp" },
  { filename: "bank-100x159.jpg"                              , label: "Bank" },
  { filename: "baron-100x161.jpg"                             , label: "Baron" },
  { filename: "bazaar-100x159.jpg"                            , label: "Bazaar" },
  { filename: "beggar-100x159.jpg"                            , label: "Beggar" },
  { filename: "bishop-100x160.jpg"                            , label: "Bishop" },
  { filename: "blockade-100x160.jpg"                          , label: "Blockade" },
  { filename: "bridge-100x160.jpg"                            , label: "Bridge" },
  { filename: "bureaucrat-100x160.jpg"                        , label: "Bureaucrat" },
  { filename: "Buried_Treasure-100x160.jpg"                   , label: "Buried Treasure" },
  { filename: "bustling-village-100x159.jpg"                  , label: "Bustling Village" },
  { filename: "Cabin_Boy-100x160.jpg"                         , label: "Cabin Boy" },
  { filename: "Cage-100x160.jpg"                              , label: "Cage" },
  { filename: "capital-100x160.jpg"                           , label: "Capital" },
  { filename: "caravan-100x160.jpg"                           , label: "Caravan" },
  { filename: "castles-100x160.jpg"                           , label: "Castles" },
  { filename: "catacombs-100x159.jpg"                         , label: "Catacombs" },
  { filename: "catapult-100x159.jpg"                          , label: "Catapult" },
  { filename: "cellar-100x160.jpg"                            , label: "Cellar" },
  { filename: "300px-Change-100x160.jpg"                      , label: "Change" },
  { filename: "chapel-100x159.jpg"                            , label: "Chapel" },
  { filename: "chariot-race-100x159.jpg"                      , label: "Chariot Race" },
  { filename: "charlatan-100x160.jpg"                         , label: "Charlatan" },
  { filename: "charm-100x160.jpg"                             , label: "Charm" },
  { filename: "city-100x160.jpg"                              , label: "City" },
  { filename: "city-quarter-100x159.jpg"                      , label: "City Quarter" },
  { filename: "clerk-100x160.jpg"                             , label: "Clerk" },
  { filename: "colony-100x160.jpg"                            , label: "Colony" },
  { filename: "conspirator-100x160.jpg"                       , label: "Conspirator" },
  { filename: "copper-100x161.jpg"                            , label: "Copper" },
  { filename: "corsair-100x160.jpg"                           , label: "Corsair" },
  { filename: "council-room-100x159.jpg"                      , label: "Council Room" },
  { filename: "count-100x159.jpg"                             , label: "Count" },
  { filename: "counterfeit-100x159.jpg"                       , label: "Counterfeit" },
  { filename: "courtier-100x160.jpg"                          , label: "Courtier" },
  { filename: "courtyard-100x160.jpg"                         , label: "Courtyard" },
  { filename: "300px-Craftsman-100x160.jpg"                   , label: "Craftsman" },
  { filename: "Crew-100x160.jpg"                              , label: "Crew" },
  { filename: "crown-100x158.jpg"                             , label: "Crown" },
  { filename: "Crucible-100x160.jpg"                          , label: "Crucible" },
  { filename: "crystal-ball-100x160.jpg"                      , label: "Crystal Ball" },
  { filename: "cultist-100x159.jpg"                           , label: "Cultist" },
  { filename: "curse-100x160.jpg"                             , label: "Curse" },
  { filename: "cutpurse-100x159.jpg"                          , label: "Cutpurse" },
  { filename: "Cutthroat-100x160.jpg"                         , label: "Cutthroat" },
  { filename: "300px-Daimyo-100x160.jpg"                      , label: "Daimyo" },
  { filename: "dame-anna-100x159.jpg"                         , label: "Dame Anna" },
  { filename: "dame-josephine-100x159.jpg"                    , label: "Dame Josephine" },
  { filename: "dame-molly-100x159.jpg"                        , label: "Dame Molly" },
  { filename: "dame-natalie-100x159.jpg"                      , label: "Dame Natalie" },
  { filename: "dame-sylvia-100x159.jpg"                       , label: "Dame Sylvia" },
  { filename: "death-cart-100x159.jpg"                        , label: "Death Cart" },
  { filename: "diplomat-100x161.jpg"                          , label: "Diplomat" },
  { filename: "duchy-100x161.jpg"                             , label: "Duchy" },
  { filename: "duke-100x160.jpg"                              , label: "Duke" },
  { filename: "emporium-100x159.jpg"                          , label: "Emporium" },
  { filename: "encampment-100x159.jpg"                        , label: "Encampment" },
  { filename: "enchantress-100x160.jpg"                       , label: "Enchantress" },
  { filename: "engineer-100x159.jpg"                          , label: "Engineer" },
  { filename: "Enlarge-100x160.jpg"                           , label: "Enlarge" },
  { filename: "estate-100x160.jpg"                            , label: "Estate" },
  { filename: "expand-100x159.jpg"                            , label: "Expand" },
  { filename: "farmers-market-100x159.jpg"                    , label: "Farmers Market" },
  { filename: "feodum-100x159.jpg"                            , label: "Feodum" },
  { filename: "festival-100x159.jpg"                          , label: "Festival" },
  { filename: "Figurine-100x160.jpg"                          , label: "Figurine" },
  { filename: "First_Mate-100x160.jpg"                        , label: "First Mate" },
  { filename: "fishing-village-100x160.jpg"                   , label: "Fishing Village" },
  { filename: "300px-Fishmonger-100x160.jpg"                  , label: "Fishmonger" },
  { filename: "Flagship-100x160.jpg"                          , label: "Flagship" },
  { filename: "forager-100x159.jpg"                           , label: "Forager" },
  { filename: "forge-100x160.jpg"                             , label: "Forge" },
  { filename: "fortress-100x159.jpg"                          , label: "Fortress" },
  { filename: "fortune-100x160.jpg"                           , label: "Fortune" },
  { filename: "Fortune_Hunter-100x160.jpg"                    , label: "Fortune Hunter" },
  { filename: "forum-100x159.jpg"                             , label: "Forum" },
  { filename: "Frigate-100x160.jpg"                           , label: "Frigate" },
  { filename: "gardens-100x159.jpg"                           , label: "Gardens" },
  { filename: "gladiator-100x160.jpg"                         , label: "Gladiator" },
  { filename: "gold-100x159.jpg"                              , label: "Gold" },
  { filename: "300px-Gold_Mine-100x160.jpg"                   , label: "Gold Mine" },
  { filename: "Gondola-100x160.jpg"                           , label: "Gondola" },
  { filename: "grand-market-100x160.jpg"                      , label: "Grand Market" },
  { filename: "graverobber-100x159.jpg"                       , label: "Graverobber" },
  { filename: "Grotto-100x160.jpg"                            , label: "Grotto" },
  { filename: "groundskeeper-100x160.jpg"                     , label: "Groundskeeper" },
  { filename: "harbinger-100x160.jpg"                         , label: "Harbinger" },
  { filename: "Harbor_Village-100x160.jpg"                    , label: "Harbor Village" },
  { filename: "harem-100x160.jpg"                             , label: "Harem" },
  { filename: "haven-100x159.jpg"                             , label: "Haven" },
  { filename: "hermit-100x159.jpg"                            , label: "Hermit" },
  { filename: "hoard-100x160.jpg"                             , label: "Hoard" },
  { filename: "hovel-100x159.jpg"                             , label: "Hovel" },
  { filename: "hunting-grounds-100x159.jpg"                   , label: "Hunting Grounds" },
  { filename: "300px-Imperial_Envoy-100x160.jpg"              , label: "Imperial Envoy" },
  { filename: "investment-100x160.jpg"                        , label: "Investment" },
  { filename: "ironmonger-100x159.jpg"                        , label: "Ironmonger" },
  { filename: "ironworks-100x160.jpg"                         , label: "Ironworks" },
  { filename: "island-100x159.jpg"                            , label: "Island" },
  { filename: "Jewelled_Egg-100x160.jpg"                      , label: "Jewelled Egg" },
  { filename: "junk-dealer-100x159.jpg"                       , label: "Junk Dealer" },
  { filename: "King%27s_Cache-100x160.jpg"                    , label: "King%27s Cache" },
  { filename: "kings-court-100x160.jpg"                       , label: "Kings Court" },
  { filename: "300px-Kitsune-100x160.jpg"                     , label: "Kitsune" },
  { filename: "knights-100x160.jpg"                           , label: "Knights" },
  { filename: "laboratory-100x160.jpg"                        , label: "Laboratory" },
  { filename: "Landing_Party-100x160.jpg"                     , label: "Landing Party" },
  { filename: "legionary-100x160.jpg"                         , label: "Legionary" },
  { filename: "library-100x160.jpg"                           , label: "Library" },
  { filename: "lighthouse-100x161.jpg"                        , label: "Lighthouse" },
  { filename: "300px-Litter-100x160.jpg"                      , label: "Litter" },
  { filename: "Longship-100x160.jpg"                          , label: "Longship" },
  { filename: "lookout-100x158.jpg"                           , label: "Lookout" },
  { filename: "lurker-100x160.jpg"                            , label: "Lurker" },
  { filename: "madman-100x159.jpg"                            , label: "Madman" },
  { filename: "magnate-100x160.jpg"                           , label: "Magnate" },
  { filename: "Mapmaker-100x160.jpg"                          , label: "Mapmaker" },
  { filename: "marauder-100x159.jpg"                          , label: "Marauder" },
  { filename: "market-100x160.jpg"                            , label: "Market" },
  { filename: "market-square-100x159.jpg"                     , label: "Market Square" },
  { filename: "Maroon-100x160.jpg"                            , label: "Maroon" },
  { filename: "masquerade-100x160.jpg"                        , label: "Masquerade" },
  { filename: "mercenary-100x159.jpg"                         , label: "Mercenary" },
  { filename: "merchant-100x160.jpg"                          , label: "Merchant" },
  { filename: "merchant-ship-100x159.jpg"                     , label: "Merchant Ship" },
  { filename: "militia-100x160.jpg"                           , label: "Militia" },
  { filename: "mill-100x160.jpg"                              , label: "Mill" },
  { filename: "mine-100x160.jpg"                              , label: "Mine" },
  { filename: "Mining_Road-100x160.jpg"                       , label: "Mining Road" },
  { filename: "mining-village-100x160.jpg"                    , label: "Mining Village" },
  { filename: "minion-100x160.jpg"                            , label: "Minion" },
  { filename: "mint-100x159.jpg"                              , label: "Mint" },
  { filename: "moat-100x161.jpg"                              , label: "Moat" },
  { filename: "moneylender-100x160.jpg"                       , label: "Moneylender" },
  { filename: "monkey-100x160.jpg"                            , label: "Monkey" },
  { filename: "monument-100x158.jpg"                          , label: "Monument" },
  { filename: "300px-Mountain_Shrine-100x160.jpg"             , label: "Mountain Shrine" },
  { filename: "mystic-100x159.jpg"                            , label: "Mystic" },
  { filename: "native-village-100x159.jpg"                    , label: "Native Village" },
  { filename: "necropolis-100x159.jpg"                        , label: "Necropolis" },
  { filename: "300px-Ninja-100x160.jpg"                       , label: "Ninja" },
  { filename: "nobles-100x160.jpg"                            , label: "Nobles" },
  { filename: "outpost-100x160.jpg"                           , label: "Outpost" },
  { filename: "overgrown-estate-100x159.jpg"                  , label: "Overgrown Estate" },
  { filename: "overlord-100x159.jpg"                          , label: "Overlord" },
  { filename: "patrician-100x160.jpg"                         , label: "Patrician" },
  { filename: "patrol-100x160.jpg"                            , label: "Patrol" },
  { filename: "pawn-100x160.jpg"                              , label: "Pawn" },
  { filename: "peddler-100x158.jpg"                           , label: "Peddler" },
  { filename: "Pendant-100x160.jpg"                           , label: "Pendant" },
  { filename: "Pickaxe-100x160.jpg"                           , label: "Pickaxe" },
  { filename: "Pilgrim-100x160.jpg"                           , label: "Pilgrim" },
  { filename: "pillage-100x159.jpg"                           , label: "Pillage" },
  { filename: "platinum-100x160.jpg"                          , label: "Platinum" },
  { filename: "plunder-100x159.jpg"                           , label: "Plunder" },
  { filename: "poacher-100x160.jpg"                           , label: "Poacher" },
  { filename: "300px-Poet-100x160.jpg"                        , label: "Poet" },
  { filename: "poor-house-100x159.jpg"                        , label: "Poor House" },
  { filename: "Prize_Goat-100x160.jpg"                        , label: "Prize Goat" },
  { filename: "procession-100x159.jpg"                        , label: "Procession" },
  { filename: "province-100x160.jpg"                          , label: "Province" },
  { filename: "quarry-100x160.jpg"                            , label: "Quarry" },
  { filename: "Quartermaster-100x160.jpg"                     , label: "Quartermaster" },
  { filename: "rabble-100x158.jpg"                            , label: "Rabble" },
  { filename: "rats-100x159.jpg"                              , label: "Rats" },
  { filename: "rebuild-100x159.jpg"                           , label: "Rebuild" },
  { filename: "remodel-100x161.jpg"                           , label: "Remodel" },
  { filename: "replace-100x161.jpg"                           , label: "Replace" },
  { filename: "300px-Rice-100x160.jpg"                        , label: "Rice" },
  { filename: "300px-Rice_Broker-100x160.jpg"                 , label: "Rice Broker" },
  { filename: "300px-River_Shrine-100x160.jpg"                , label: "River Shrine" },
  { filename: "300px-Riverboat-100x160.jpg"                   , label: "Riverboat" },
  { filename: "rocks-100x160.jpg"                             , label: "Rocks" },
  { filename: "rogue-100x159.jpg"                             , label: "Rogue" },
  { filename: "300px-Ronin-100x160.jpg"                       , label: "Ronin" },
  { filename: "300px-Root_Cellar-100x160.jpg"                 , label: "Root Cellar" },
  { filename: "Rope-100x160.jpg"                              , label: "Rope" },
  { filename: "royal-blacksmith-100x159.jpg"                  , label: "Royal Blacksmith" },
  { filename: "ruined-library-100x159.jpg"                    , label: "Ruined Library" },
  { filename: "ruined-market-100x159.jpg"                     , label: "Ruined Market" },
  { filename: "ruined-village-100x159.jpg"                    , label: "Ruined Village" },
  { filename: "300px-Rustic_Village-100x160.jpg"              , label: "Rustic Village" },
  { filename: "Sack_of_Loot-100x160.jpg"                      , label: "Sack Of Loot" },
  { filename: "sacrifice-100x160.jpg"                         , label: "Sacrifice" },
  { filename: "sage-100x159.jpg"                              , label: "Sage" },
  { filename: "sailor-100x160.jpg"                            , label: "Sailor" },
  { filename: "salvager-100x159.jpg"                          , label: "Salvager" },
  { filename: "300px-Samurai-100x160.jpg"                     , label: "Samurai" },
  { filename: "scavenger-100x159.jpg"                         , label: "Scavenger" },
  { filename: "sea-chart-100x160.jpg"                         , label: "Sea Chart" },
  { filename: "sea-witch-100x160.jpg"                         , label: "Sea Witch" },
  { filename: "Search-100x160.jpg"                            , label: "Search" },
  { filename: "Secluded_Shrine-100x160.jpg"                   , label: "Secluded Shrine" },
  { filename: "secret-passage-100x160.jpg"                    , label: "Secret Passage" },
  { filename: "sentry-100x161.jpg"                            , label: "Sentry" },
  { filename: "settlers-100x158.jpg"                          , label: "Settlers" },
  { filename: "Shaman-100x160.jpg"                            , label: "Shaman" },
  { filename: "shanty-town-100x160.jpg"                       , label: "Shanty Town" },
  { filename: "silver-100x160.jpg"                            , label: "Silver" },
  { filename: "Silver_Mine-100x160.jpg"                       , label: "Silver Mine" },
  { filename: "sir-bailey-100x159.jpg"                        , label: "Sir Bailey" },
  { filename: "sir-destry-100x158.jpg"                        , label: "Sir Destry" },
  { filename: "sir-martin-100x159.jpg"                        , label: "Sir Martin" },
  { filename: "sir-michael-100x159.jpg"                       , label: "Sir Michael" },
  { filename: "sir-vander-100x159.jpg"                        , label: "Sir Vander" },
  { filename: "Siren-100x160.jpg"                             , label: "Siren" },
  { filename: "smithy-100x160.jpg"                            , label: "Smithy" },
  { filename: "smugglers-100x159.jpg"                         , label: "Smugglers" },
  { filename: "300px-Snake_Witch-100x160.jpg"                 , label: "Snake Witch" },
  { filename: "spoils-100x159.jpg"                            , label: "Spoils" },
  { filename: "squire-100x159.jpg"                            , label: "Squire" },
  { filename: "steward-100x160.jpg"                           , label: "Steward" },
  { filename: "storeroom-100x159.jpg"                         , label: "Storeroom" },
  { filename: "Stowaway-100x160.jpg"                          , label: "Stowaway" },
  { filename: "survivors-100x159.jpg"                         , label: "Survivors" },
  { filename: "Swamp_Shacks-100x160.jpg"                      , label: "Swamp Shacks" },
  { filename: "swindler-100x161.jpg"                          , label: "Swindler" },
  { filename: "tactician-100x160.jpg"                         , label: "Tactician" },
  { filename: "300px-Tanuki-100x160.jpg"                      , label: "Tanuki" },
  { filename: "Taskmaster-100x160.jpg"                        , label: "Taskmaster" },
  { filename: "300px-Tea_House-100x160.jpg"                   , label: "Tea House" },
  { filename: "temple-100x160.jpg"                            , label: "Temple" },
  { filename: "throne-room-100x160.jpg"                       , label: "Throne Room" },
  { filename: "tiara-100x160.jpg"                             , label: "Tiara" },
  { filename: "tide-pools-100x160.jpg"                        , label: "Tide Pools" },
  { filename: "Tools-100x160.jpg"                             , label: "Tools" },
  { filename: "torturer-100x161.jpg"                          , label: "Torturer" },
  { filename: "trading-post-100x160.jpg"                      , label: "Trading Post" },
  { filename: "Trash-Base-100x159.jpg"                        , label: "Trash Base" },
  { filename: "treasure-map-100x159.jpg"                      , label: "Treasure Map" },
  { filename: "treasury-100x159.jpg"                          , label: "Treasury" },
  { filename: "Trickster-100x160.jpg"                         , label: "Trickster" },
  { filename: "upgrade-100x160.jpg"                           , label: "Upgrade" },
  { filename: "urchin-100x159.jpg"                            , label: "Urchin" },
  { filename: "vagrant-100x159.jpg"                           , label: "Vagrant" },
  { filename: "vassal-100x160.jpg"                            , label: "Vassal" },
  { filename: "vault-100x158.jpg"                             , label: "Vault" },
  { filename: "villa-100x159.jpg"                             , label: "Villa" },
  { filename: "village-100x160.jpg"                           , label: "Village" },
  { filename: "wandering-minstrel-100x159.jpg"                , label: "Wandering Minstrel" },
  { filename: "war-chest-100x160.jpg"                         , label: "War Chest" },
  { filename: "warehouse-100x160.jpg"                         , label: "Warehouse" },
  { filename: "watchtower-100x159.jpg"                        , label: "Watchtower" },
  { filename: "Wealthy_Village-100x160.jpg"                   , label: "Wealthy Village" },
  { filename: "wharf-100x160.jpg"                             , label: "Wharf" },
  { filename: "wild-hunt-100x160.jpg"                         , label: "Wild Hunt" },
  { filename: "wishing-well-100x160.jpg"                      , label: "Wishing Well" },
  { filename: "witch-100x160.jpg"                             , label: "Witch" },
  { filename: "workers-village-100x160.jpg"                   , label: "Workers Village" },
  { filename: "workshop-100x160.jpg"                          , label: "Workshop" },
];

// GET /api/cards — valid card image filenames + readable labels
router.get('/', (req, res) => {
  let cards = [];
  try {
    cards = fs.readdirSync(CARDS_DIR)
      .filter(f => /\.(png|jpg|webp)$/i.test(f))
      .map(filename => ({ filename, label: labelFor(filename) }))
      .sort((a, b) => a.label.localeCompare(b.label));
  } catch { /* assets absent — fall through to hardcoded list */ }

  res.json(cards.length > 0 ? cards : CARDS_FALLBACK);
});

module.exports = router;
